/********************************************************************************
** Form generated from reading UI file 'employeui.ui'
**
** Created: Fri 18. Sep 17:32:26 2015
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EMPLOYEUI_H
#define UI_EMPLOYEUI_H

#include <QtCore/QDate>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDateEdit>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QTabWidget>
#include <QtGui/QTableView>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_employeui
{
public:
    QTabWidget *tabWidget;
    QWidget *tab;
    QLineEdit *lineEdit_prenom;
    QLineEdit *lineEdit_passport;
    QLabel *label_professionControl;
    QLineEdit *lineEdit_adresseTravail;
    QLabel *label_RechercherEmploye;
    QLabel *label_NomControl;
    QLabel *label_PassportControl;
    QLabel *label_nationnalite;
    QLineEdit *lineEdit_NSS;
    QLabel *label_15;
    QCheckBox *checkBox_IDSearch;
    QLabel *label_7;
    QFrame *line_6;
    QLabel *label_adresse;
    QLineEdit *lineEdit_ID;
    QLabel *label_ServiceControl;
    QLabel *label_SexeControl;
    QLineEdit *lineEdit_motdepasse;
    QLabel *label_etatCivil;
    QLabel *label_CIN;
    QLineEdit *lineEdit_adresse;
    QPushButton *pushButton_Annuler;
    QPushButton *pushButton_StatistiquesEmploye;
    QDateEdit *dateEdit_dateEmbouche;
    QLabel *label_PrenomControl;
    QLabel *label_SortieApplication;
    QComboBox *comboBox_Nom;
    QPushButton *pushButton_supprmier;
    QLabel *label_PasswordConfirmControl;
    QLineEdit *lineEdit_CIN;
    QPushButton *pushButton_Save;
    QLabel *label_telephoneTravail;
    QLabel *label_contrat;
    QLineEdit *lineEdit_profession;
    QLineEdit *lineEdit_nom;
    QLabel *label_EtatCivilControl;
    QFrame *line_7;
    QLabel *label_PasswordControl;
    QLabel *label_DateNaissanceControl;
    QLineEdit *lineEdit_mailTravail;
    QLabel *label_dateNaissance;
    QLabel *label_embouche;
    QLabel *label_mailTravail;
    QLabel *label_passport;
    QLabel *label_adresseTravail;
    QLabel *label_ContratControl;
    QLabel *label_prenom;
    QPushButton *pushButton_ChargerImage;
    QLineEdit *lineEdit_nationnalite;
    QLabel *label_NSS;
    QFrame *line_2;
    QComboBox *comboBox_EtatCivil;
    QDateEdit *dateEdit_dateNaissance;
    QLabel *label_24;
    QComboBox *comboBox_sexe;
    QLabel *label_profession;
    QLabel *label;
    QLabel *label_ID;
    QLabel *label_sexe;
    QLabel *label_IDControl;
    QLabel *label_motdepasse;
    QLabel *label_AdresseTravailControl;
    QLabel *label_20;
    QLabel *label_image;
    QLabel *label_service;
    QLabel *label_SortieApplicationMessage;
    QComboBox *comboBox_contrat;
    QLabel *label_TelephoneTravailControl;
    QLabel *label_confirmermotdepasse;
    QLineEdit *lineEdit_telephoneTravail;
    QFrame *line_3;
    QLabel *label_NationnaliteControl;
    QLabel *label_mailControl;
    QLabel *label_NssControl;
    QLabel *label_CinControl;
    QLineEdit *lineEdit_confirmermotdepasse;
    QLabel *label_AdresseControl;
    QLabel *label_25;
    QFrame *line_5;
    QComboBox *comboBox_service;
    QFrame *line_4;
    QPushButton *pushButton_Edit;
    QLabel *label_DateEmbouchementControl;
    QPushButton *pushButton_ListingEmploye;
    QLabel *label_102;
    QWidget *tab_2;
    QLineEdit *lineEdit_IDCongeEmploye;
    QLabel *label_IDCongeEmploye;
    QComboBox *comboBox_TypeConge;
    QLabel *label_TypeConge;
    QDateEdit *dateEdit_DebutConge;
    QLabel *label_DateDebutConge;
    QLabel *label_DateFinConge;
    QDateEdit *dateEdit_FinConge;
    QFrame *line_8;
    QLabel *label_2;
    QPushButton *pushButton_AjoutConge;
    QPushButton *pushButton_ModifierConge;
    QPushButton *pushButton_SupprimerConge;
    QLabel *label_commentaireResponsable;
    QLabel *label_CommentaireEmploye;
    QLabel *label_IDCongeEmploye_2;
    QFrame *line_9;
    QFrame *line_10;
    QLabel *label_3;
    QLabel *label_4;
    QFrame *line_11;
    QLabel *label_SortieApplicationMessage_2;
    QTextEdit *textEdit_Responsable;
    QTextEdit *textEdit_Employe;
    QLineEdit *lineEdit_IDCongeEmployeRechercher;
    QPushButton *pushButton_NettoyerConge;
    QPushButton *pushButton_ListingConge;
    QLabel *label_IDCongeControl;
    QLabel *label_DateDebutCongeControl;
    QLabel *label_typeCongeControl_2;
    QLabel *label_DateFinCongeControl;
    QLabel *label_typeCongeControl;
    QLabel *SortieApplicationConge;
    QLabel *label_103;
    QWidget *tab_3;
    QFrame *line_12;
    QLabel *label_5;
    QPushButton *pushButton_NettoyerPaiement;
    QPushButton *pushButton_ListingPaiement;
    QLineEdit *lineEdit_IDPaiementEmployeRecherche;
    QPushButton *pushButton_AjoutPaiement;
    QLabel *label_IDCongeEmploye_3;
    QLineEdit *lineEdit_IDPaiementEmploye;
    QLabel *label_IDCongeEmploye_4;
    QLabel *label_TypeConge_2;
    QLineEdit *lineEdit_MontantTTC;
    QLabel *label_6;
    QFrame *line_13;
    QLabel *label_DateDebutConge_2;
    QDateEdit *dateEdit_Paiement;
    QFrame *line_14;
    QLabel *label_8;
    QTextEdit *textEdit_PaiementResponsable;
    QLabel *label_commentaireResponsable_2;
    QLabel *label_SortieApplicationMessage_3;
    QFrame *line_15;
    QLabel *label_IDPaiementControl;
    QLabel *label_MontantControl;
    QLabel *label_DatePaiementControl;
    QLabel *SortieApplicationPaiement;
    QLabel *label_104;
    QWidget *tab_4;
    QLabel *label_9;
    QFrame *line_16;
    QTableView *tableViewPointage;
    QLabel *label_IDCongeEmploye_5;
    QLineEdit *lineEdit_IDRechercherPointage;
    QFrame *line_17;
    QLabel *label_SortieApplicationMessage_4;
    QLabel *SortieApplicationPointage;
    QLabel *label_RechercherPointageControl;
    QLabel *label_105;

    void setupUi(QWidget *employeui)
    {
        if (employeui->objectName().isEmpty())
            employeui->setObjectName(QString::fromUtf8("employeui"));
        employeui->resize(889, 872);
        tabWidget = new QTabWidget(employeui);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 891, 871));
        tabWidget->setDocumentMode(true);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tab->setStyleSheet(QString::fromUtf8(""));
        lineEdit_prenom = new QLineEdit(tab);
        lineEdit_prenom->setObjectName(QString::fromUtf8("lineEdit_prenom"));
        lineEdit_prenom->setGeometry(QRect(200, 230, 201, 21));
        lineEdit_passport = new QLineEdit(tab);
        lineEdit_passport->setObjectName(QString::fromUtf8("lineEdit_passport"));
        lineEdit_passport->setGeometry(QRect(200, 400, 201, 22));
        label_professionControl = new QLabel(tab);
        label_professionControl->setObjectName(QString::fromUtf8("label_professionControl"));
        label_professionControl->setGeometry(QRect(800, 570, 20, 20));
        lineEdit_adresseTravail = new QLineEdit(tab);
        lineEdit_adresseTravail->setObjectName(QString::fromUtf8("lineEdit_adresseTravail"));
        lineEdit_adresseTravail->setGeometry(QRect(200, 600, 201, 22));
        label_RechercherEmploye = new QLabel(tab);
        label_RechercherEmploye->setObjectName(QString::fromUtf8("label_RechercherEmploye"));
        label_RechercherEmploye->setGeometry(QRect(50, 140, 151, 20));
        label_NomControl = new QLabel(tab);
        label_NomControl->setObjectName(QString::fromUtf8("label_NomControl"));
        label_NomControl->setGeometry(QRect(410, 200, 20, 20));
        label_PassportControl = new QLabel(tab);
        label_PassportControl->setObjectName(QString::fromUtf8("label_PassportControl"));
        label_PassportControl->setGeometry(QRect(410, 400, 20, 20));
        label_nationnalite = new QLabel(tab);
        label_nationnalite->setObjectName(QString::fromUtf8("label_nationnalite"));
        label_nationnalite->setGeometry(QRect(500, 400, 91, 16));
        lineEdit_NSS = new QLineEdit(tab);
        lineEdit_NSS->setObjectName(QString::fromUtf8("lineEdit_NSS"));
        lineEdit_NSS->setGeometry(QRect(200, 340, 201, 22));
        label_15 = new QLabel(tab);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(480, 310, 101, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_15->setFont(font);
        checkBox_IDSearch = new QCheckBox(tab);
        checkBox_IDSearch->setObjectName(QString::fromUtf8("checkBox_IDSearch"));
        checkBox_IDSearch->setGeometry(QRect(60, 740, 401, 21));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(40, 310, 71, 16));
        label_7->setFont(font);
        line_6 = new QFrame(tab);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(20, 780, 861, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        label_adresse = new QLabel(tab);
        label_adresse->setObjectName(QString::fromUtf8("label_adresse"));
        label_adresse->setGeometry(QRect(130, 570, 71, 16));
        lineEdit_ID = new QLineEdit(tab);
        lineEdit_ID->setObjectName(QString::fromUtf8("lineEdit_ID"));
        lineEdit_ID->setGeometry(QRect(200, 370, 201, 22));
        label_ServiceControl = new QLabel(tab);
        label_ServiceControl->setObjectName(QString::fromUtf8("label_ServiceControl"));
        label_ServiceControl->setGeometry(QRect(410, 260, 20, 20));
        label_SexeControl = new QLabel(tab);
        label_SexeControl->setObjectName(QString::fromUtf8("label_SexeControl"));
        label_SexeControl->setGeometry(QRect(710, 340, 20, 20));
        lineEdit_motdepasse = new QLineEdit(tab);
        lineEdit_motdepasse->setObjectName(QString::fromUtf8("lineEdit_motdepasse"));
        lineEdit_motdepasse->setGeometry(QRect(200, 460, 201, 22));
        label_etatCivil = new QLabel(tab);
        label_etatCivil->setObjectName(QString::fromUtf8("label_etatCivil"));
        label_etatCivil->setGeometry(QRect(510, 370, 71, 16));
        label_CIN = new QLabel(tab);
        label_CIN->setObjectName(QString::fromUtf8("label_CIN"));
        label_CIN->setGeometry(QRect(50, 430, 141, 16));
        lineEdit_adresse = new QLineEdit(tab);
        lineEdit_adresse->setObjectName(QString::fromUtf8("lineEdit_adresse"));
        lineEdit_adresse->setGeometry(QRect(200, 570, 201, 22));
        pushButton_Annuler = new QPushButton(tab);
        pushButton_Annuler->setObjectName(QString::fromUtf8("pushButton_Annuler"));
        pushButton_Annuler->setGeometry(QRect(355, 80, 100, 28));
        pushButton_StatistiquesEmploye = new QPushButton(tab);
        pushButton_StatistiquesEmploye->setObjectName(QString::fromUtf8("pushButton_StatistiquesEmploye"));
        pushButton_StatistiquesEmploye->setGeometry(QRect(585, 80, 93, 28));
        dateEdit_dateEmbouche = new QDateEdit(tab);
        dateEdit_dateEmbouche->setObjectName(QString::fromUtf8("dateEdit_dateEmbouche"));
        dateEdit_dateEmbouche->setGeometry(QRect(590, 630, 110, 22));
        dateEdit_dateEmbouche->setDateTime(QDateTime(QDate(1800, 1, 1), QTime(0, 0, 1)));
        dateEdit_dateEmbouche->setDate(QDate(1800, 1, 1));
        label_PrenomControl = new QLabel(tab);
        label_PrenomControl->setObjectName(QString::fromUtf8("label_PrenomControl"));
        label_PrenomControl->setGeometry(QRect(410, 230, 20, 20));
        label_SortieApplication = new QLabel(tab);
        label_SortieApplication->setObjectName(QString::fromUtf8("label_SortieApplication"));
        label_SortieApplication->setGeometry(QRect(170, 810, 611, 20));
        comboBox_Nom = new QComboBox(tab);
        comboBox_Nom->setObjectName(QString::fromUtf8("comboBox_Nom"));
        comboBox_Nom->setGeometry(QRect(200, 140, 401, 22));
        QFont font1;
        font1.setKerning(false);
        comboBox_Nom->setFont(font1);
        comboBox_Nom->setEditable(true);
        comboBox_Nom->setMaxVisibleItems(2);
        comboBox_Nom->setFrame(true);
        pushButton_supprmier = new QPushButton(tab);
        pushButton_supprmier->setObjectName(QString::fromUtf8("pushButton_supprmier"));
        pushButton_supprmier->setGeometry(QRect(245, 80, 93, 28));
        label_PasswordConfirmControl = new QLabel(tab);
        label_PasswordConfirmControl->setObjectName(QString::fromUtf8("label_PasswordConfirmControl"));
        label_PasswordConfirmControl->setGeometry(QRect(410, 490, 20, 20));
        lineEdit_CIN = new QLineEdit(tab);
        lineEdit_CIN->setObjectName(QString::fromUtf8("lineEdit_CIN"));
        lineEdit_CIN->setGeometry(QRect(200, 430, 201, 22));
        pushButton_Save = new QPushButton(tab);
        pushButton_Save->setObjectName(QString::fromUtf8("pushButton_Save"));
        pushButton_Save->setGeometry(QRect(25, 80, 93, 28));
        label_telephoneTravail = new QLabel(tab);
        label_telephoneTravail->setObjectName(QString::fromUtf8("label_telephoneTravail"));
        label_telephoneTravail->setGeometry(QRect(60, 630, 131, 16));
        label_contrat = new QLabel(tab);
        label_contrat->setObjectName(QString::fromUtf8("label_contrat"));
        label_contrat->setGeometry(QRect(470, 600, 111, 16));
        lineEdit_profession = new QLineEdit(tab);
        lineEdit_profession->setObjectName(QString::fromUtf8("lineEdit_profession"));
        lineEdit_profession->setGeometry(QRect(590, 570, 201, 22));
        lineEdit_nom = new QLineEdit(tab);
        lineEdit_nom->setObjectName(QString::fromUtf8("lineEdit_nom"));
        lineEdit_nom->setGeometry(QRect(200, 200, 201, 21));
        label_EtatCivilControl = new QLabel(tab);
        label_EtatCivilControl->setObjectName(QString::fromUtf8("label_EtatCivilControl"));
        label_EtatCivilControl->setGeometry(QRect(710, 370, 20, 20));
        line_7 = new QFrame(tab);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(40, 720, 401, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        label_PasswordControl = new QLabel(tab);
        label_PasswordControl->setObjectName(QString::fromUtf8("label_PasswordControl"));
        label_PasswordControl->setGeometry(QRect(410, 460, 20, 20));
        label_DateNaissanceControl = new QLabel(tab);
        label_DateNaissanceControl->setObjectName(QString::fromUtf8("label_DateNaissanceControl"));
        label_DateNaissanceControl->setGeometry(QRect(710, 430, 20, 20));
        lineEdit_mailTravail = new QLineEdit(tab);
        lineEdit_mailTravail->setObjectName(QString::fromUtf8("lineEdit_mailTravail"));
        lineEdit_mailTravail->setGeometry(QRect(200, 660, 201, 22));
        label_dateNaissance = new QLabel(tab);
        label_dateNaissance->setObjectName(QString::fromUtf8("label_dateNaissance"));
        label_dateNaissance->setGeometry(QRect(460, 430, 121, 16));
        label_embouche = new QLabel(tab);
        label_embouche->setObjectName(QString::fromUtf8("label_embouche"));
        label_embouche->setGeometry(QRect(460, 630, 111, 16));
        label_mailTravail = new QLabel(tab);
        label_mailTravail->setObjectName(QString::fromUtf8("label_mailTravail"));
        label_mailTravail->setGeometry(QRect(80, 660, 131, 16));
        label_passport = new QLabel(tab);
        label_passport->setObjectName(QString::fromUtf8("label_passport"));
        label_passport->setGeometry(QRect(50, 400, 141, 16));
        label_adresseTravail = new QLabel(tab);
        label_adresseTravail->setObjectName(QString::fromUtf8("label_adresseTravail"));
        label_adresseTravail->setGeometry(QRect(70, 600, 131, 16));
        label_ContratControl = new QLabel(tab);
        label_ContratControl->setObjectName(QString::fromUtf8("label_ContratControl"));
        label_ContratControl->setGeometry(QRect(710, 600, 20, 20));
        label_prenom = new QLabel(tab);
        label_prenom->setObjectName(QString::fromUtf8("label_prenom"));
        label_prenom->setGeometry(QRect(60, 230, 131, 16));
        pushButton_ChargerImage = new QPushButton(tab);
        pushButton_ChargerImage->setObjectName(QString::fromUtf8("pushButton_ChargerImage"));
        pushButton_ChargerImage->setGeometry(QRect(710, 80, 101, 28));
        lineEdit_nationnalite = new QLineEdit(tab);
        lineEdit_nationnalite->setObjectName(QString::fromUtf8("lineEdit_nationnalite"));
        lineEdit_nationnalite->setGeometry(QRect(590, 400, 201, 22));
        label_NSS = new QLabel(tab);
        label_NSS->setObjectName(QString::fromUtf8("label_NSS"));
        label_NSS->setGeometry(QRect(40, 340, 151, 16));
        line_2 = new QFrame(tab);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(40, 320, 401, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        comboBox_EtatCivil = new QComboBox(tab);
        comboBox_EtatCivil->setObjectName(QString::fromUtf8("comboBox_EtatCivil"));
        comboBox_EtatCivil->setGeometry(QRect(590, 370, 111, 22));
        dateEdit_dateNaissance = new QDateEdit(tab);
        dateEdit_dateNaissance->setObjectName(QString::fromUtf8("dateEdit_dateNaissance"));
        dateEdit_dateNaissance->setGeometry(QRect(590, 430, 110, 22));
        dateEdit_dateNaissance->setDate(QDate(1800, 1, 1));
        label_24 = new QLabel(tab);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(480, 540, 151, 16));
        label_24->setFont(font);
        comboBox_sexe = new QComboBox(tab);
        comboBox_sexe->setObjectName(QString::fromUtf8("comboBox_sexe"));
        comboBox_sexe->setGeometry(QRect(590, 340, 111, 22));
        label_profession = new QLabel(tab);
        label_profession->setObjectName(QString::fromUtf8("label_profession"));
        label_profession->setGeometry(QRect(500, 570, 71, 16));
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(80, 200, 121, 16));
        label_ID = new QLabel(tab);
        label_ID->setObjectName(QString::fromUtf8("label_ID"));
        label_ID->setGeometry(QRect(50, 370, 141, 16));
        label_sexe = new QLabel(tab);
        label_sexe->setObjectName(QString::fromUtf8("label_sexe"));
        label_sexe->setGeometry(QRect(540, 340, 51, 16));
        label_IDControl = new QLabel(tab);
        label_IDControl->setObjectName(QString::fromUtf8("label_IDControl"));
        label_IDControl->setGeometry(QRect(410, 370, 20, 20));
        label_motdepasse = new QLabel(tab);
        label_motdepasse->setObjectName(QString::fromUtf8("label_motdepasse"));
        label_motdepasse->setGeometry(QRect(100, 460, 91, 16));
        label_AdresseTravailControl = new QLabel(tab);
        label_AdresseTravailControl->setObjectName(QString::fromUtf8("label_AdresseTravailControl"));
        label_AdresseTravailControl->setGeometry(QRect(410, 600, 20, 20));
        label_20 = new QLabel(tab);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(40, 540, 151, 16));
        label_20->setFont(font);
        label_image = new QLabel(tab);
        label_image->setObjectName(QString::fromUtf8("label_image"));
        label_image->setGeometry(QRect(680, 140, 161, 161));
        label_service = new QLabel(tab);
        label_service->setObjectName(QString::fromUtf8("label_service"));
        label_service->setGeometry(QRect(60, 260, 141, 16));
        label_SortieApplicationMessage = new QLabel(tab);
        label_SortieApplicationMessage->setObjectName(QString::fromUtf8("label_SortieApplicationMessage"));
        label_SortieApplicationMessage->setGeometry(QRect(30, 810, 141, 16));
        comboBox_contrat = new QComboBox(tab);
        comboBox_contrat->setObjectName(QString::fromUtf8("comboBox_contrat"));
        comboBox_contrat->setGeometry(QRect(590, 600, 111, 22));
        label_TelephoneTravailControl = new QLabel(tab);
        label_TelephoneTravailControl->setObjectName(QString::fromUtf8("label_TelephoneTravailControl"));
        label_TelephoneTravailControl->setGeometry(QRect(410, 630, 20, 20));
        label_confirmermotdepasse = new QLabel(tab);
        label_confirmermotdepasse->setObjectName(QString::fromUtf8("label_confirmermotdepasse"));
        label_confirmermotdepasse->setGeometry(QRect(30, 490, 171, 16));
        lineEdit_telephoneTravail = new QLineEdit(tab);
        lineEdit_telephoneTravail->setObjectName(QString::fromUtf8("lineEdit_telephoneTravail"));
        lineEdit_telephoneTravail->setGeometry(QRect(200, 630, 201, 22));
        line_3 = new QFrame(tab);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(480, 320, 391, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_NationnaliteControl = new QLabel(tab);
        label_NationnaliteControl->setObjectName(QString::fromUtf8("label_NationnaliteControl"));
        label_NationnaliteControl->setGeometry(QRect(800, 400, 20, 20));
        label_mailControl = new QLabel(tab);
        label_mailControl->setObjectName(QString::fromUtf8("label_mailControl"));
        label_mailControl->setGeometry(QRect(410, 660, 20, 20));
        label_NssControl = new QLabel(tab);
        label_NssControl->setObjectName(QString::fromUtf8("label_NssControl"));
        label_NssControl->setGeometry(QRect(410, 340, 20, 20));
        label_CinControl = new QLabel(tab);
        label_CinControl->setObjectName(QString::fromUtf8("label_CinControl"));
        label_CinControl->setGeometry(QRect(410, 430, 20, 20));
        lineEdit_confirmermotdepasse = new QLineEdit(tab);
        lineEdit_confirmermotdepasse->setObjectName(QString::fromUtf8("lineEdit_confirmermotdepasse"));
        lineEdit_confirmermotdepasse->setGeometry(QRect(200, 490, 201, 22));
        label_AdresseControl = new QLabel(tab);
        label_AdresseControl->setObjectName(QString::fromUtf8("label_AdresseControl"));
        label_AdresseControl->setGeometry(QRect(410, 570, 20, 20));
        label_25 = new QLabel(tab);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(50, 710, 151, 16));
        label_25->setFont(font);
        line_5 = new QFrame(tab);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(480, 550, 391, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        comboBox_service = new QComboBox(tab);
        comboBox_service->setObjectName(QString::fromUtf8("comboBox_service"));
        comboBox_service->setGeometry(QRect(200, 260, 201, 22));
        line_4 = new QFrame(tab);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(40, 550, 401, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        pushButton_Edit = new QPushButton(tab);
        pushButton_Edit->setObjectName(QString::fromUtf8("pushButton_Edit"));
        pushButton_Edit->setGeometry(QRect(135, 80, 93, 28));
        label_DateEmbouchementControl = new QLabel(tab);
        label_DateEmbouchementControl->setObjectName(QString::fromUtf8("label_DateEmbouchementControl"));
        label_DateEmbouchementControl->setGeometry(QRect(710, 630, 20, 20));
        pushButton_ListingEmploye = new QPushButton(tab);
        pushButton_ListingEmploye->setObjectName(QString::fromUtf8("pushButton_ListingEmploye"));
        pushButton_ListingEmploye->setGeometry(QRect(475, 80, 93, 28));
        label_102 = new QLabel(tab);
        label_102->setObjectName(QString::fromUtf8("label_102"));
        label_102->setGeometry(QRect(0, 0, 891, 71));
        label_102->setPixmap(QPixmap(QString::fromUtf8("graphique.jpg")));
        tabWidget->addTab(tab, QString());
        label_102->raise();
        lineEdit_prenom->raise();
        lineEdit_passport->raise();
        label_professionControl->raise();
        lineEdit_adresseTravail->raise();
        label_RechercherEmploye->raise();
        label_NomControl->raise();
        label_PassportControl->raise();
        label_nationnalite->raise();
        lineEdit_NSS->raise();
        label_15->raise();
        checkBox_IDSearch->raise();
        label_7->raise();
        line_6->raise();
        label_adresse->raise();
        lineEdit_ID->raise();
        label_ServiceControl->raise();
        label_SexeControl->raise();
        lineEdit_motdepasse->raise();
        label_etatCivil->raise();
        label_CIN->raise();
        lineEdit_adresse->raise();
        pushButton_Annuler->raise();
        pushButton_StatistiquesEmploye->raise();
        dateEdit_dateEmbouche->raise();
        label_PrenomControl->raise();
        label_SortieApplication->raise();
        comboBox_Nom->raise();
        pushButton_supprmier->raise();
        label_PasswordConfirmControl->raise();
        lineEdit_CIN->raise();
        pushButton_Save->raise();
        label_telephoneTravail->raise();
        label_contrat->raise();
        lineEdit_profession->raise();
        lineEdit_nom->raise();
        label_EtatCivilControl->raise();
        line_7->raise();
        label_PasswordControl->raise();
        label_DateNaissanceControl->raise();
        lineEdit_mailTravail->raise();
        label_dateNaissance->raise();
        label_embouche->raise();
        label_mailTravail->raise();
        label_passport->raise();
        label_adresseTravail->raise();
        label_ContratControl->raise();
        label_prenom->raise();
        pushButton_ChargerImage->raise();
        lineEdit_nationnalite->raise();
        label_NSS->raise();
        line_2->raise();
        comboBox_EtatCivil->raise();
        dateEdit_dateNaissance->raise();
        label_24->raise();
        comboBox_sexe->raise();
        label_profession->raise();
        label->raise();
        label_ID->raise();
        label_sexe->raise();
        label_IDControl->raise();
        label_motdepasse->raise();
        label_AdresseTravailControl->raise();
        label_20->raise();
        label_image->raise();
        label_service->raise();
        label_SortieApplicationMessage->raise();
        comboBox_contrat->raise();
        label_TelephoneTravailControl->raise();
        label_confirmermotdepasse->raise();
        lineEdit_telephoneTravail->raise();
        line_3->raise();
        label_NationnaliteControl->raise();
        label_mailControl->raise();
        label_NssControl->raise();
        label_CinControl->raise();
        lineEdit_confirmermotdepasse->raise();
        label_AdresseControl->raise();
        label_25->raise();
        line_5->raise();
        comboBox_service->raise();
        line_4->raise();
        pushButton_Edit->raise();
        label_DateEmbouchementControl->raise();
        pushButton_ListingEmploye->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        lineEdit_IDCongeEmploye = new QLineEdit(tab_2);
        lineEdit_IDCongeEmploye->setObjectName(QString::fromUtf8("lineEdit_IDCongeEmploye"));
        lineEdit_IDCongeEmploye->setGeometry(QRect(200, 200, 201, 22));
        label_IDCongeEmploye = new QLabel(tab_2);
        label_IDCongeEmploye->setObjectName(QString::fromUtf8("label_IDCongeEmploye"));
        label_IDCongeEmploye->setGeometry(QRect(40, 200, 251, 16));
        comboBox_TypeConge = new QComboBox(tab_2);
        comboBox_TypeConge->setObjectName(QString::fromUtf8("comboBox_TypeConge"));
        comboBox_TypeConge->setGeometry(QRect(200, 230, 201, 22));
        comboBox_TypeConge->setEditable(true);
        comboBox_TypeConge->setMinimumContentsLength(0);
        label_TypeConge = new QLabel(tab_2);
        label_TypeConge->setObjectName(QString::fromUtf8("label_TypeConge"));
        label_TypeConge->setGeometry(QRect(90, 230, 101, 16));
        dateEdit_DebutConge = new QDateEdit(tab_2);
        dateEdit_DebutConge->setObjectName(QString::fromUtf8("dateEdit_DebutConge"));
        dateEdit_DebutConge->setGeometry(QRect(210, 340, 110, 22));
        dateEdit_DebutConge->setDate(QDate(1800, 1, 1));
        label_DateDebutConge = new QLabel(tab_2);
        label_DateDebutConge->setObjectName(QString::fromUtf8("label_DateDebutConge"));
        label_DateDebutConge->setGeometry(QRect(80, 340, 121, 20));
        label_DateFinConge = new QLabel(tab_2);
        label_DateFinConge->setObjectName(QString::fromUtf8("label_DateFinConge"));
        label_DateFinConge->setGeometry(QRect(100, 370, 121, 20));
        dateEdit_FinConge = new QDateEdit(tab_2);
        dateEdit_FinConge->setObjectName(QString::fromUtf8("dateEdit_FinConge"));
        dateEdit_FinConge->setGeometry(QRect(210, 370, 110, 22));
        dateEdit_FinConge->setDate(QDate(1800, 1, 1));
        line_8 = new QFrame(tab_2);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(20, 60, 861, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(tab_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(40, 20, 53, 16));
        pushButton_AjoutConge = new QPushButton(tab_2);
        pushButton_AjoutConge->setObjectName(QString::fromUtf8("pushButton_AjoutConge"));
        pushButton_AjoutConge->setGeometry(QRect(25, 80, 93, 28));
        pushButton_ModifierConge = new QPushButton(tab_2);
        pushButton_ModifierConge->setObjectName(QString::fromUtf8("pushButton_ModifierConge"));
        pushButton_ModifierConge->setGeometry(QRect(135, 80, 93, 28));
        pushButton_SupprimerConge = new QPushButton(tab_2);
        pushButton_SupprimerConge->setObjectName(QString::fromUtf8("pushButton_SupprimerConge"));
        pushButton_SupprimerConge->setGeometry(QRect(245, 80, 93, 28));
        label_commentaireResponsable = new QLabel(tab_2);
        label_commentaireResponsable->setObjectName(QString::fromUtf8("label_commentaireResponsable"));
        label_commentaireResponsable->setGeometry(QRect(10, 490, 171, 16));
        label_CommentaireEmploye = new QLabel(tab_2);
        label_CommentaireEmploye->setObjectName(QString::fromUtf8("label_CommentaireEmploye"));
        label_CommentaireEmploye->setGeometry(QRect(30, 620, 171, 16));
        label_IDCongeEmploye_2 = new QLabel(tab_2);
        label_IDCongeEmploye_2->setObjectName(QString::fromUtf8("label_IDCongeEmploye_2"));
        label_IDCongeEmploye_2->setGeometry(QRect(60, 140, 141, 16));
        line_9 = new QFrame(tab_2);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(40, 320, 401, 20));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(tab_2);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(40, 450, 401, 20));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        label_3 = new QLabel(tab_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(40, 310, 111, 16));
        label_3->setFont(font);
        label_4 = new QLabel(tab_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(40, 440, 211, 16));
        label_4->setFont(font);
        line_11 = new QFrame(tab_2);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(20, 780, 861, 16));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        label_SortieApplicationMessage_2 = new QLabel(tab_2);
        label_SortieApplicationMessage_2->setObjectName(QString::fromUtf8("label_SortieApplicationMessage_2"));
        label_SortieApplicationMessage_2->setGeometry(QRect(30, 810, 141, 16));
        textEdit_Responsable = new QTextEdit(tab_2);
        textEdit_Responsable->setObjectName(QString::fromUtf8("textEdit_Responsable"));
        textEdit_Responsable->setGeometry(QRect(190, 490, 291, 121));
        textEdit_Employe = new QTextEdit(tab_2);
        textEdit_Employe->setObjectName(QString::fromUtf8("textEdit_Employe"));
        textEdit_Employe->setGeometry(QRect(190, 620, 291, 121));
        lineEdit_IDCongeEmployeRechercher = new QLineEdit(tab_2);
        lineEdit_IDCongeEmployeRechercher->setObjectName(QString::fromUtf8("lineEdit_IDCongeEmployeRechercher"));
        lineEdit_IDCongeEmployeRechercher->setGeometry(QRect(200, 140, 391, 22));
        pushButton_NettoyerConge = new QPushButton(tab_2);
        pushButton_NettoyerConge->setObjectName(QString::fromUtf8("pushButton_NettoyerConge"));
        pushButton_NettoyerConge->setGeometry(QRect(355, 80, 100, 28));
        pushButton_ListingConge = new QPushButton(tab_2);
        pushButton_ListingConge->setObjectName(QString::fromUtf8("pushButton_ListingConge"));
        pushButton_ListingConge->setGeometry(QRect(475, 80, 93, 28));
        label_IDCongeControl = new QLabel(tab_2);
        label_IDCongeControl->setObjectName(QString::fromUtf8("label_IDCongeControl"));
        label_IDCongeControl->setGeometry(QRect(410, 200, 21, 21));
        label_DateDebutCongeControl = new QLabel(tab_2);
        label_DateDebutCongeControl->setObjectName(QString::fromUtf8("label_DateDebutCongeControl"));
        label_DateDebutCongeControl->setGeometry(QRect(330, 340, 21, 21));
        label_typeCongeControl_2 = new QLabel(tab_2);
        label_typeCongeControl_2->setObjectName(QString::fromUtf8("label_typeCongeControl_2"));
        label_typeCongeControl_2->setGeometry(QRect(440, 270, 21, 21));
        label_DateFinCongeControl = new QLabel(tab_2);
        label_DateFinCongeControl->setObjectName(QString::fromUtf8("label_DateFinCongeControl"));
        label_DateFinCongeControl->setGeometry(QRect(330, 370, 21, 21));
        label_typeCongeControl = new QLabel(tab_2);
        label_typeCongeControl->setObjectName(QString::fromUtf8("label_typeCongeControl"));
        label_typeCongeControl->setGeometry(QRect(410, 230, 21, 21));
        SortieApplicationConge = new QLabel(tab_2);
        SortieApplicationConge->setObjectName(QString::fromUtf8("SortieApplicationConge"));
        SortieApplicationConge->setGeometry(QRect(170, 810, 601, 16));
        label_103 = new QLabel(tab_2);
        label_103->setObjectName(QString::fromUtf8("label_103"));
        label_103->setGeometry(QRect(0, 0, 891, 71));
        label_103->setPixmap(QPixmap(QString::fromUtf8("graphique.jpg")));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        line_12 = new QFrame(tab_3);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setGeometry(QRect(20, 60, 861, 16));
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        label_5 = new QLabel(tab_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(40, 20, 91, 16));
        pushButton_NettoyerPaiement = new QPushButton(tab_3);
        pushButton_NettoyerPaiement->setObjectName(QString::fromUtf8("pushButton_NettoyerPaiement"));
        pushButton_NettoyerPaiement->setGeometry(QRect(135, 80, 91, 28));
        pushButton_ListingPaiement = new QPushButton(tab_3);
        pushButton_ListingPaiement->setObjectName(QString::fromUtf8("pushButton_ListingPaiement"));
        pushButton_ListingPaiement->setGeometry(QRect(246, 80, 93, 28));
        lineEdit_IDPaiementEmployeRecherche = new QLineEdit(tab_3);
        lineEdit_IDPaiementEmployeRecherche->setObjectName(QString::fromUtf8("lineEdit_IDPaiementEmployeRecherche"));
        lineEdit_IDPaiementEmployeRecherche->setGeometry(QRect(200, 140, 391, 22));
        pushButton_AjoutPaiement = new QPushButton(tab_3);
        pushButton_AjoutPaiement->setObjectName(QString::fromUtf8("pushButton_AjoutPaiement"));
        pushButton_AjoutPaiement->setGeometry(QRect(25, 80, 93, 28));
        label_IDCongeEmploye_3 = new QLabel(tab_3);
        label_IDCongeEmploye_3->setObjectName(QString::fromUtf8("label_IDCongeEmploye_3"));
        label_IDCongeEmploye_3->setGeometry(QRect(20, 140, 181, 16));
        lineEdit_IDPaiementEmploye = new QLineEdit(tab_3);
        lineEdit_IDPaiementEmploye->setObjectName(QString::fromUtf8("lineEdit_IDPaiementEmploye"));
        lineEdit_IDPaiementEmploye->setGeometry(QRect(200, 200, 201, 22));
        label_IDCongeEmploye_4 = new QLabel(tab_3);
        label_IDCongeEmploye_4->setObjectName(QString::fromUtf8("label_IDCongeEmploye_4"));
        label_IDCongeEmploye_4->setGeometry(QRect(40, 200, 151, 16));
        label_TypeConge_2 = new QLabel(tab_3);
        label_TypeConge_2->setObjectName(QString::fromUtf8("label_TypeConge_2"));
        label_TypeConge_2->setGeometry(QRect(90, 230, 101, 16));
        lineEdit_MontantTTC = new QLineEdit(tab_3);
        lineEdit_MontantTTC->setObjectName(QString::fromUtf8("lineEdit_MontantTTC"));
        lineEdit_MontantTTC->setGeometry(QRect(200, 230, 201, 22));
        label_6 = new QLabel(tab_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(40, 310, 141, 16));
        label_6->setFont(font);
        line_13 = new QFrame(tab_3);
        line_13->setObjectName(QString::fromUtf8("line_13"));
        line_13->setGeometry(QRect(40, 320, 401, 20));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        label_DateDebutConge_2 = new QLabel(tab_3);
        label_DateDebutConge_2->setObjectName(QString::fromUtf8("label_DateDebutConge_2"));
        label_DateDebutConge_2->setGeometry(QRect(76, 340, 121, 20));
        dateEdit_Paiement = new QDateEdit(tab_3);
        dateEdit_Paiement->setObjectName(QString::fromUtf8("dateEdit_Paiement"));
        dateEdit_Paiement->setGeometry(QRect(210, 340, 110, 22));
        dateEdit_Paiement->setDate(QDate(1800, 1, 1));
        line_14 = new QFrame(tab_3);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setGeometry(QRect(40, 450, 401, 20));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(40, 440, 211, 16));
        label_8->setFont(font);
        textEdit_PaiementResponsable = new QTextEdit(tab_3);
        textEdit_PaiementResponsable->setObjectName(QString::fromUtf8("textEdit_PaiementResponsable"));
        textEdit_PaiementResponsable->setGeometry(QRect(190, 490, 291, 121));
        label_commentaireResponsable_2 = new QLabel(tab_3);
        label_commentaireResponsable_2->setObjectName(QString::fromUtf8("label_commentaireResponsable_2"));
        label_commentaireResponsable_2->setGeometry(QRect(10, 490, 171, 16));
        label_SortieApplicationMessage_3 = new QLabel(tab_3);
        label_SortieApplicationMessage_3->setObjectName(QString::fromUtf8("label_SortieApplicationMessage_3"));
        label_SortieApplicationMessage_3->setGeometry(QRect(30, 810, 141, 16));
        line_15 = new QFrame(tab_3);
        line_15->setObjectName(QString::fromUtf8("line_15"));
        line_15->setGeometry(QRect(10, 780, 861, 16));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        label_IDPaiementControl = new QLabel(tab_3);
        label_IDPaiementControl->setObjectName(QString::fromUtf8("label_IDPaiementControl"));
        label_IDPaiementControl->setGeometry(QRect(410, 200, 21, 21));
        label_MontantControl = new QLabel(tab_3);
        label_MontantControl->setObjectName(QString::fromUtf8("label_MontantControl"));
        label_MontantControl->setGeometry(QRect(410, 230, 21, 21));
        label_DatePaiementControl = new QLabel(tab_3);
        label_DatePaiementControl->setObjectName(QString::fromUtf8("label_DatePaiementControl"));
        label_DatePaiementControl->setGeometry(QRect(330, 340, 21, 21));
        SortieApplicationPaiement = new QLabel(tab_3);
        SortieApplicationPaiement->setObjectName(QString::fromUtf8("SortieApplicationPaiement"));
        SortieApplicationPaiement->setGeometry(QRect(170, 810, 601, 16));
        label_104 = new QLabel(tab_3);
        label_104->setObjectName(QString::fromUtf8("label_104"));
        label_104->setGeometry(QRect(0, 0, 891, 71));
        label_104->setPixmap(QPixmap(QString::fromUtf8("graphique.jpg")));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_9 = new QLabel(tab_4);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(67, 20, 91, 16));
        line_16 = new QFrame(tab_4);
        line_16->setObjectName(QString::fromUtf8("line_16"));
        line_16->setGeometry(QRect(16, 60, 861, 16));
        line_16->setFrameShape(QFrame::HLine);
        line_16->setFrameShadow(QFrame::Sunken);
        tableViewPointage = new QTableView(tab_4);
        tableViewPointage->setObjectName(QString::fromUtf8("tableViewPointage"));
        tableViewPointage->setGeometry(QRect(110, 220, 621, 451));
        label_IDCongeEmploye_5 = new QLabel(tab_4);
        label_IDCongeEmploye_5->setObjectName(QString::fromUtf8("label_IDCongeEmploye_5"));
        label_IDCongeEmploye_5->setGeometry(QRect(20, 140, 181, 16));
        lineEdit_IDRechercherPointage = new QLineEdit(tab_4);
        lineEdit_IDRechercherPointage->setObjectName(QString::fromUtf8("lineEdit_IDRechercherPointage"));
        lineEdit_IDRechercherPointage->setGeometry(QRect(200, 140, 391, 22));
        line_17 = new QFrame(tab_4);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setGeometry(QRect(10, 780, 861, 16));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        label_SortieApplicationMessage_4 = new QLabel(tab_4);
        label_SortieApplicationMessage_4->setObjectName(QString::fromUtf8("label_SortieApplicationMessage_4"));
        label_SortieApplicationMessage_4->setGeometry(QRect(30, 810, 141, 16));
        SortieApplicationPointage = new QLabel(tab_4);
        SortieApplicationPointage->setObjectName(QString::fromUtf8("SortieApplicationPointage"));
        SortieApplicationPointage->setGeometry(QRect(170, 810, 601, 16));
        label_RechercherPointageControl = new QLabel(tab_4);
        label_RechercherPointageControl->setObjectName(QString::fromUtf8("label_RechercherPointageControl"));
        label_RechercherPointageControl->setGeometry(QRect(600, 140, 21, 21));
        label_105 = new QLabel(tab_4);
        label_105->setObjectName(QString::fromUtf8("label_105"));
        label_105->setGeometry(QRect(0, 0, 891, 71));
        label_105->setPixmap(QPixmap(QString::fromUtf8("graphique.jpg")));
        tabWidget->addTab(tab_4, QString());

        retranslateUi(employeui);

        tabWidget->setCurrentIndex(0);
        comboBox_EtatCivil->setCurrentIndex(-1);
        comboBox_sexe->setCurrentIndex(-1);
        comboBox_contrat->setCurrentIndex(-1);
        comboBox_service->setCurrentIndex(-1);
        comboBox_TypeConge->setCurrentIndex(-1);


        QMetaObject::connectSlotsByName(employeui);
    } // setupUi

    void retranslateUi(QWidget *employeui)
    {
        employeui->setWindowTitle(QApplication::translate("employeui", "Gestion des ressources humaines", 0, QApplication::UnicodeUTF8));
        label_professionControl->setText(QString());
        label_RechercherEmploye->setText(QApplication::translate("employeui", "Rechercher un employ\303\251 : ", 0, QApplication::UnicodeUTF8));
        label_NomControl->setText(QString());
        label_PassportControl->setText(QString());
        label_nationnalite->setText(QApplication::translate("employeui", "Nationnalit\303\251 : ", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("employeui", "Status Sociale", 0, QApplication::UnicodeUTF8));
        checkBox_IDSearch->setText(QApplication::translate("employeui", "Activer la recherche instantan\303\251e par Num\303\251ro d'identification", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("employeui", "IDs Sociale", 0, QApplication::UnicodeUTF8));
        label_adresse->setText(QApplication::translate("employeui", "Adresse :", 0, QApplication::UnicodeUTF8));
        label_ServiceControl->setText(QString());
        label_SexeControl->setText(QString());
        label_etatCivil->setText(QApplication::translate("employeui", "Etat Civile :", 0, QApplication::UnicodeUTF8));
        label_CIN->setText(QApplication::translate("employeui", "               Num\303\251ro CIN :", 0, QApplication::UnicodeUTF8));
        pushButton_Annuler->setText(QApplication::translate("employeui", "Nettoyer", 0, QApplication::UnicodeUTF8));
        pushButton_StatistiquesEmploye->setText(QApplication::translate("employeui", "Statistiques", 0, QApplication::UnicodeUTF8));
        label_PrenomControl->setText(QString());
        label_SortieApplication->setText(QString());
        pushButton_supprmier->setText(QApplication::translate("employeui", "Supprimer", 0, QApplication::UnicodeUTF8));
        label_PasswordConfirmControl->setText(QString());
        pushButton_Save->setText(QApplication::translate("employeui", "Ajouter", 0, QApplication::UnicodeUTF8));
        label_telephoneTravail->setText(QApplication::translate("employeui", "Telephone de travail :", 0, QApplication::UnicodeUTF8));
        label_contrat->setText(QApplication::translate("employeui", "Type de contrat :", 0, QApplication::UnicodeUTF8));
        lineEdit_nom->setText(QString());
        label_EtatCivilControl->setText(QString());
        label_PasswordControl->setText(QString());
        label_DateNaissanceControl->setText(QString());
        label_dateNaissance->setText(QApplication::translate("employeui", "Date de Naissance :", 0, QApplication::UnicodeUTF8));
        label_embouche->setText(QApplication::translate("employeui", "Date d'embouche :", 0, QApplication::UnicodeUTF8));
        label_mailTravail->setText(QApplication::translate("employeui", "E-mail de travail :", 0, QApplication::UnicodeUTF8));
        label_passport->setText(QApplication::translate("employeui", "   Num\303\251ro de Passport :", 0, QApplication::UnicodeUTF8));
        label_adresseTravail->setText(QApplication::translate("employeui", "Adresse de travail :", 0, QApplication::UnicodeUTF8));
        label_ContratControl->setText(QString());
        label_prenom->setText(QApplication::translate("employeui", "Prenom de l'employ\303\251 :", 0, QApplication::UnicodeUTF8));
        pushButton_ChargerImage->setText(QApplication::translate("employeui", "Charger image ", 0, QApplication::UnicodeUTF8));
        label_NSS->setText(QApplication::translate("employeui", "Num\303\251ro S\303\251curit\303\251 Sociale : ", 0, QApplication::UnicodeUTF8));
        comboBox_EtatCivil->clear();
        comboBox_EtatCivil->insertItems(0, QStringList()
         << QApplication::translate("employeui", "C\303\251libataire", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Mari\303\251", 0, QApplication::UnicodeUTF8)
        );
        label_24->setText(QApplication::translate("employeui", "Position", 0, QApplication::UnicodeUTF8));
        comboBox_sexe->clear();
        comboBox_sexe->insertItems(0, QStringList()
         << QApplication::translate("employeui", "Homme", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Femme", 0, QApplication::UnicodeUTF8)
        );
        label_profession->setText(QApplication::translate("employeui", "Profession :", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("employeui", "Nom de l'employ\303\251 :", 0, QApplication::UnicodeUTF8));
        label_ID->setText(QApplication::translate("employeui", "Num\303\251ro d'identification :", 0, QApplication::UnicodeUTF8));
        label_sexe->setText(QApplication::translate("employeui", "Sexe : ", 0, QApplication::UnicodeUTF8));
        label_IDControl->setText(QString());
        label_motdepasse->setText(QApplication::translate("employeui", "Mot de Passe : ", 0, QApplication::UnicodeUTF8));
        label_AdresseTravailControl->setText(QString());
        label_20->setText(QApplication::translate("employeui", "Contacte Informations", 0, QApplication::UnicodeUTF8));
        label_image->setText(QApplication::translate("employeui", "IMAGE_", 0, QApplication::UnicodeUTF8));
        label_service->setText(QApplication::translate("employeui", "Service de l'employ\303\251 : ", 0, QApplication::UnicodeUTF8));
        label_SortieApplicationMessage->setText(QApplication::translate("employeui", "Sortie de l'application :", 0, QApplication::UnicodeUTF8));
        comboBox_contrat->clear();
        comboBox_contrat->insertItems(0, QStringList()
         << QApplication::translate("employeui", "Annuel", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Payer A l'acte", 0, QApplication::UnicodeUTF8)
        );
        label_TelephoneTravailControl->setText(QString());
        label_confirmermotdepasse->setText(QApplication::translate("employeui", "Confirmer le mot de Passe :", 0, QApplication::UnicodeUTF8));
        label_NationnaliteControl->setText(QString());
        label_mailControl->setText(QString());
        label_NssControl->setText(QString());
        label_CinControl->setText(QString());
        label_AdresseControl->setText(QString());
        label_25->setText(QApplication::translate("employeui", "Options", 0, QApplication::UnicodeUTF8));
        comboBox_service->clear();
        comboBox_service->insertItems(0, QStringList()
         << QApplication::translate("employeui", "Radiologie/IRM", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cardiologie", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "finaci\303\250re", 0, QApplication::UnicodeUTF8)
        );
        pushButton_Edit->setText(QApplication::translate("employeui", "Modifier", 0, QApplication::UnicodeUTF8));
        label_DateEmbouchementControl->setText(QString());
        pushButton_ListingEmploye->setText(QApplication::translate("employeui", "Listing", 0, QApplication::UnicodeUTF8));
        label_102->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("employeui", "Employe", 0, QApplication::UnicodeUTF8));
        label_IDCongeEmploye->setText(QApplication::translate("employeui", "Num\303\251ro d'indentification :", 0, QApplication::UnicodeUTF8));
        comboBox_TypeConge->clear();
        comboBox_TypeConge->insertItems(0, QStringList()
         << QApplication::translate("employeui", "Cong\303\251 sans solde", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cong\303\251 pay\303\251", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cong\303\251 annuel", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cong\303\251 d'examen", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cong\303\251 de formation", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cong\303\251 maladie", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("employeui", "Cong\303\251 mat\303\251rnit\303\251", 0, QApplication::UnicodeUTF8)
        );
        label_TypeConge->setText(QApplication::translate("employeui", "Type de conge :", 0, QApplication::UnicodeUTF8));
        label_DateDebutConge->setText(QApplication::translate("employeui", "Date d\303\251but conge :", 0, QApplication::UnicodeUTF8));
        label_DateFinConge->setText(QApplication::translate("employeui", "Date fin conge :", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("employeui", "Conge :", 0, QApplication::UnicodeUTF8));
        pushButton_AjoutConge->setText(QApplication::translate("employeui", "Ajouter", 0, QApplication::UnicodeUTF8));
        pushButton_ModifierConge->setText(QApplication::translate("employeui", "Modifier", 0, QApplication::UnicodeUTF8));
        pushButton_SupprimerConge->setText(QApplication::translate("employeui", "Supprimer", 0, QApplication::UnicodeUTF8));
        label_commentaireResponsable->setText(QApplication::translate("employeui", "Commentaire Responsable : ", 0, QApplication::UnicodeUTF8));
        label_CommentaireEmploye->setText(QApplication::translate("employeui", "Commentaire Employe : ", 0, QApplication::UnicodeUTF8));
        label_IDCongeEmploye_2->setText(QApplication::translate("employeui", "Rechercher un cong\303\251 : ", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("employeui", "Dates du conge", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("employeui", "Informations suppl\303\251mentaires", 0, QApplication::UnicodeUTF8));
        label_SortieApplicationMessage_2->setText(QApplication::translate("employeui", "Sortie de l'application :", 0, QApplication::UnicodeUTF8));
        pushButton_NettoyerConge->setText(QApplication::translate("employeui", "Nettoyer", 0, QApplication::UnicodeUTF8));
        pushButton_ListingConge->setText(QApplication::translate("employeui", "Listing", 0, QApplication::UnicodeUTF8));
        label_IDCongeControl->setText(QString());
        label_DateDebutCongeControl->setText(QString());
        label_typeCongeControl_2->setText(QString());
        label_DateFinCongeControl->setText(QString());
        label_typeCongeControl->setText(QString());
        SortieApplicationConge->setText(QString());
        label_103->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("employeui", "Conge", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("employeui", "Fiche de Paie :", 0, QApplication::UnicodeUTF8));
        pushButton_NettoyerPaiement->setText(QApplication::translate("employeui", "Nettoyer", 0, QApplication::UnicodeUTF8));
        pushButton_ListingPaiement->setText(QApplication::translate("employeui", "Listing", 0, QApplication::UnicodeUTF8));
        pushButton_AjoutPaiement->setText(QApplication::translate("employeui", "Ajouter", 0, QApplication::UnicodeUTF8));
        label_IDCongeEmploye_3->setText(QApplication::translate("employeui", "Rechercher une fiche de paie: ", 0, QApplication::UnicodeUTF8));
        label_IDCongeEmploye_4->setText(QApplication::translate("employeui", "Num\303\251ro d'indentification :", 0, QApplication::UnicodeUTF8));
        label_TypeConge_2->setText(QApplication::translate("employeui", "Montant (TTC) :", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("employeui", "Dates de paiement :", 0, QApplication::UnicodeUTF8));
        label_DateDebutConge_2->setText(QApplication::translate("employeui", "Date de paiement  :", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("employeui", "Informations suppl\303\251mentaires", 0, QApplication::UnicodeUTF8));
        label_commentaireResponsable_2->setText(QApplication::translate("employeui", "Commentaire Responsable : ", 0, QApplication::UnicodeUTF8));
        label_SortieApplicationMessage_3->setText(QApplication::translate("employeui", "Sortie de l'application :", 0, QApplication::UnicodeUTF8));
        label_IDPaiementControl->setText(QString());
        label_MontantControl->setText(QString());
        label_DatePaiementControl->setText(QString());
        SortieApplicationPaiement->setText(QString());
        label_104->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("employeui", "Paiement", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("employeui", "Pointage :", 0, QApplication::UnicodeUTF8));
        label_IDCongeEmploye_5->setText(QApplication::translate("employeui", "Rechercher un Pointage       : ", 0, QApplication::UnicodeUTF8));
        label_SortieApplicationMessage_4->setText(QApplication::translate("employeui", "Sortie de l'application :", 0, QApplication::UnicodeUTF8));
        SortieApplicationPointage->setText(QString());
        label_RechercherPointageControl->setText(QString());
        label_105->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("employeui", "Pointage", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class employeui: public Ui_employeui {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EMPLOYEUI_H
